Sprint_3/educahelp/loja/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('produto.urls')),
    path('perfil/', include('perfil.urls')),
    path('pedido/', include('pedido.urls')),
    path('paginas/', include('paginas.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Sprint_3/educahelp/paginas/urls.py
from django.urls import path
from . import views


app_name = 'page'


urlpatterns = [
    path('aboutus/', views.aboutUs, name='aboutUs'),
    path('linkedin/', views.linkedIn, name='linkedIn'),
    path('facebook/', views.facebook, name='facebook'),
    path('instagram/', views.instagram, name='instagram'),
    path('twitter/', views.twitter, name='twitter'),
]

Sprint_3/educahelp/pedido/urls.py
from django.urls import path
from . import views

app_name = 'pedido'

urlpatterns = [
    path('pagar/<int:pk>', views.Pagar.as_view(), name='pagar'),
    path('salvarpedido/', views.SalvarPedido.as_view(), name='salvarpedido'),
    path('lista/', views.Lista.as_view(), name='lista'),
    path('detalhe/<int:pk>', views.Detalhe.as_view(), name='detalhe'),
    path('confirmado/', views.Confirmado, name='confirmado'),
    path('export/', views.export, name='export'),
]

Sprint_3/educahelp/perfil/urls.py
from django.urls import path
from . import views

app_name = 'perfil'

urlpatterns = [
    path('', views.Criar.as_view(), name='criar'),
    path('atualizar1/', views.Atualizar1.as_view(), name='atualizar1'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('atualizar/', views.atualizar, name='atualizar'),
    path('contato/', views.Contato, name='contato'),
    path('relatorio/', views.Relatorio, name='relatorio'),
    path('interface/', views.Interface, name='interface'),
    path('meus_pedidos/', views.Meus_pedidos, name='meus_pedidos'),
    path('interface2/', views.Interface2, name='interface2')
]

Sprint_3/educahelp/produto/urls.py
from django.urls import path
from . import views


app_name = 'produto'

urlpatterns = [
    path('', views.ListaProdutos.as_view(), name="lista"),
    path('<slug>', views.DetalheProduto.as_view(), name="detalhe"),
    path('adicionaraocarrinho/', views.AdicionarAoCarrinho.as_view(),
         name="adicionaraocarrinho"),
    path('removerdocarrinho/', views.RemoverDoCarrinho.as_view(),
         name="removerdocarrinho"),
    path('carrinho/', views.Carrinho.as_view(), name="carrinho"),
    path('resumodacompra/', views.ResumoDaCompra.as_view(), name="resumodacompra"),
    path('busca/', views.Busca.as_view(), name="busca"),
    path('criar/', views.conteudo_create, name='conteudo_create'),
    path('editar/<int:id>/', views.edite_conteudo, name='editar_conteudo'),
    path('deletar/<int:id>/', views.conteudo_delete, name='conteudo_delete'),
]

Sprint_3/educahelp/pedido/models.py
from django.db import models
from django.contrib.auth.models import User
# from matplotlib import pyplot as plt
# from pylab import *
# import PIL, PIL.Image, StringIO
# import io




class Pedido(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    total = models.FloatField()
    qtd_total = models.PositiveIntegerField()
    status = models.CharField(
        default="C",
        max_length=1,
        choices=(
            ('A', 'Aprovado'),
            ('C', 'Criado'),
            ('R', 'Reprovado'),
            ('P', 'Pendente'),
            ('E', 'Enviado'),
            ('F', 'Finalizado'),
        )
    )

    def __str__(self):
        return f'Pedido N. {self.pk}'


class ItemPedido(models.Model):
    pedido = models.ForeignKey(Pedido, on_delete=models.CASCADE)
    produto = models.CharField(max_length=255)
    produto_id = models.PositiveIntegerField()
    variacao = models.CharField(max_length=255)
    variacao_id = models.PositiveIntegerField()
    preco = models.FloatField()
    preco_promocional = models.FloatField(default=0)
    quantidade = models.PositiveIntegerField()
    imagem = models.CharField(max_length=2000)

    def __str__(self):
        return f'Item do {self.pedido}'

    class Meta:
        verbose_name = 'Item do pedido'
        verbose_name_plural = 'Itens do pedido'


# def relatorio(request):
#      Construct the graph
#     x = arange(0, 2*pi, 0.01)
#     s = cos(x)**2
#     plot(x, s)

#     xlabel('xlabel(X)')
#     ylabel('ylabel(Y)')
#     title('Simple Graph!')
#     grid(True)

#     Store image in a string buffer
#     buffer = StringIO.StringIO()
#     canvas = pylab.get_current_fig_manager().canvas
#     canvas.draw()
#     pilImage = PIL.Image.fromstring("RGB", canvas.get_width_height(), canvas.tostring_rgb())
#     pilImage.save(buffer, "PNG")
#     pylab.close()

#     Send buffer in a http response the the browser with the mime type image/png set
#     return HttpResponse(buffer.getvalue(), mimetype="image/png")

Sprint_3/educahelp/pedido/views.py
from django.shortcuts import redirect, reverse, render
from django.views.generic import ListView, DetailView
from django.views import View
from django.http import HttpResponse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from produto.models import Variacao
from .models import Pedido, ItemPedido

from utils import utils
import csv


class DispatchLoginRequiredMixin(View):
    def dispatch(self, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return redirect('perfil:criar')

        return super().dispatch(*args, **kwargs)

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        qs = qs.filter(usuario=self.request.user)
        return qs


class Pagar(DispatchLoginRequiredMixin, DetailView):
    template_name = 'pedido/pagar.html'
    model = Pedido
    pk_url_kwarg = 'pk'
    context_object_name = 'pedido'


class SalvarPedido(View):
    template_name = 'pedido/pagar.html'

    def get(self, *args, **kwargs):
        if not self.request.user.is_authenticated:
            messages.error(
                self.request,
                'Você precisa fazer login.'
            )
            return redirect('perfil:criar')

        if not self.request.session.get('carrinho'):
            messages.error(
                self.request,
                'Seu carrinho está vazio.'
            )
            return redirect('produto:lista')

        carrinho = self.request.session.get('carrinho')
        carrinho_variacao_ids = [v for v in carrinho]
        bd_variacoes = list(
            Variacao.objects.select_related('produto')
            .filter(id__in=carrinho_variacao_ids)
        )

        for variacao in bd_variacoes:
            vid = str(variacao.id)

            estoque = variacao.estoque
            qtd_carrinho = carrinho[vid]['quantidade']
            preco_unt = carrinho[vid]['preco_unitario']
            preco_unt_promo = carrinho[vid]['preco_unitario_promocional']

            error_msg_estoque = ''

            if estoque < qtd_carrinho:
                carrinho[vid]['quantidade'] = estoque
                carrinho[vid]['preco_quantitativo'] = estoque * preco_unt
                carrinho[vid]['preco_quantitativo_promocional'] = estoque * \
                    preco_unt_promo

                error_msg_estoque = 'Estoque insuficiente para alguns '\
                    'produtos do seu carrinho. '\
                    'Reduzimos a quantidade desses produtos. Por favor, '\
                    'verifique quais produtos foram afetados a seguir.'

            if error_msg_estoque:
                messages.error(
                    self.request,
                    error_msg_estoque
                )

                self.request.session.save()
                return redirect('produto:carrinho')

        qtd_total_carrinho = utils.cart_total_qtd(carrinho)
        valor_total_carrinho = utils.cart_totals(carrinho)

        pedido = Pedido(
            usuario=self.request.user,
            total=valor_total_carrinho,
            qtd_total=qtd_total_carrinho,
            status='C',
        )

        pedido.save()

        ItemPedido.objects.bulk_create(
            [
                ItemPedido(
                    pedido=pedido,
                    produto=v['produto_nome'],
                    produto_id=v['produto_id'],
                    variacao=v['variacao_nome'],
                    variacao_id=v['variacao_id'],
                    preco=v['preco_quantitativo'],
                    preco_promocional=v['preco_quantitativo_promocional'],
                    quantidade=v['quantidade'],
                    imagem=v['imagem'],
                ) for v in carrinho.values()
            ]
        )

        del self.request.session['carrinho']

        return redirect(
            reverse(
                'pedido:pagar',
                kwargs={
                    'pk': pedido.pk
                }
            )
        )


class Detalhe(DispatchLoginRequiredMixin, DetailView):
    model = Pedido
    context_object_name = 'pedido'
    template_name = 'pedido/detalhe.html'
    pk_url_kwarg = 'pk'


class Lista(DispatchLoginRequiredMixin, ListView):
    model = Pedido
    context_object_name = 'pedidos'
    template_name = 'pedido/lista.html'
    paginate_by = 10
    ordering = ['-id']

def Confirmado(request):
    return render(request, 'pedido/confirmado.html')

@login_required()
def export(request):
    response = HttpResponse(content_type='text/csv')
    writer = csv.writer(response)
    writer.writerow(['Pedido', 'Produto', 'Quantidade', 'Preco'])

    for itempedido in ItemPedido.objects.all().values_list('pedido', 'produto', 'quantidade', 'preco'):
        writer.writerow(itempedido)

    response['Content-Disposition'] = 'attachment; filename="relatorio.csv"'

    return response

Sprint_3/educahelp/templates/parciais/_carrinho.html
{% load static %}
{% load omfilters %}

<div class="table-responsive">
    <table class="table">
        <tr>
            <th class="d-none d-lg-block">Imagem</th>
            <th>Produto</th>
            <th>V.</th>
            <th>QTD.</th>
            <th>Total</th>
        </tr>

        {% for linha in carrinho.values %}
        <tr>
            <td class="d-none d-lg-block">
                <img class="cart-img" src="{% get_media_prefix %}{{ linha.imagem }}">
            </td>
            <td>
                <a href="{% url 'produto:detalhe' linha.slug %}">
                    {{ linha.produto_nome }}
                </a>

                <a class="ml-3" href="{% url 'produto:removerdocarrinho' %}?vid={{ linha.variacao_id }}">
                    <i class="fas fa-times-circle text-danger" aria-hidden="true"></i>
                </a>
            </td>
            <td>{{ linha.variacao_nome }}</td>
            <td>
                {{ linha.quantidade }} x
                {% if linha.preco_unitario_promocional %}
                {{ linha.preco_unitario_promocional }}
                {% else %}
                {{ linha.preco_unitario }}
                {% endif %}
            </td>

            {% if linha.preco_quantitativo_promocional %}
            <td>{{ linha.preco_quantitativo_promocional|formata_preco }}</td>
            {% else %}
            <td>{{ linha.preco_quantitativo|formata_preco }}</td>
            {% endif %}

        </tr>
        {% endfor %}


    </table>
</div>

Sprint_3/educahelp/templates/parciais/_footer.html
{% load static %}

<footer class="container-fluid text-center">
    <!-- Footer -->
  <footer class="page-footer font-small blue pt-4">
  
    <!-- Footer Links -->
    <div class="container-fluid text-center text-md-left">
  
      <!-- Grid row -->
      <div class="row">
  
        <!-- Grid column -->
        <div class="col-md-6 mt-md-0 mt-3">
  
          <!-- Content -->
          <h3 class="text-uppercase"><strong>EducaHelp</strong></h3>
          <p>O site que te dá um help na educação!</p>
  
        </div>
        <!-- Grid column -->
  
        <hr class="clearfix w-100 d-md-none pb-3">
  
        <!-- Grid column -->
        <div class="col-md-3 mb-md-0 mb-3">
  
          <!-- Links -->
          <h5 class="text-uppercase">Redes Sociais:</h5>
  
          <ul class="list-unstyled">
            <li>
              <a href="{% url 'page:facebook' %}">Facebook</a>
            </li>
            <li>
              <a href="{% url 'page:instagram' %}">Instagram</a>
            </li>
            <li>
              <a href="{% url 'page:twitter' %}">Twitter</a>
            </li>
            <li>
              <a href="{% url 'page:linkedIn' %}">LinkedIn</a>
            </li>
          </ul>
  
        </div>
        <!-- Grid column -->
  
        <!-- Grid column -->
        <div class="col-md-3 mb-md-0 mb-3">
  
          <!-- Links -->
          <h5 class="text-uppercase">Contato:</h5>
  
          <ul class="list-unstyled">
            <li>
              <a href="{% url 'perfil:contato' %}">Fale Conosco</a>
            </li>
            <li>
              <a href="{% url 'page:aboutUs' %}">Sobre nós</a>
            </li>
          </ul>
  
        </div>
        <!-- Grid column -->
  
      </div>
      <!-- Grid row -->
  
    </div>
    <!-- Footer Links -->
  
    <!-- Copyright -->
    <div class="footer-copyright text-center py-3">© 2020 Copyright:
      <a href="/"> EducaHelp</a>
    </div>
    <!-- Copyright -->
  </footer>
  </footer>
<script src="{% static 'assets/bootstrap/js/jquery-3.2.1.slim.min.js'%}"></script>
<script src="{% static 'assets/bootstrap/js/popper.min.js'%}"></script>
<script src="{% static 'assets/bootstrap/js/bootstrap.min.js'%}"></script>
<script defer src="{% static 'assets/font-awesome/js/all.js'%}"></script>
<script src="{% static 'assets/custom/js/scripts.js'%}"></script>
<script type="text/javascript" src="https://platform.linkedin.com/badges/js/profile.js" async defer></script>

Sprint_3/educahelp/templates/parciais/_head.html
{% load static %}

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.css'%}">
<link rel="stylesheet" href="{% static 'assets/custom/css/style.css'%}">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
<link rel="stylesheet" href="{% static 'css/styles.css' %}">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
<script src="{% static 'js/scripts.js' %}"></script>

  <!-- favicon-->
  <link rel="icon" type="image/png" sizes="32x32" href="https://raw.githubusercontent.com/RoyaltyDev/Projeto_integrador_2020-2/master/imagens/favicon_package_v0.16/favicon-16x16.png">
  <style>
    #logoimg{
      padding-top: 5px;
      margin-top: 0px;
    }

    #sign{
      color: black;
    }
    #sigtxt{
      color: black;
    }
    #sigtxt2{
      color: black;
    }
    #logtxt{
      color: black;
    }
    #logtxt2{
      color: black;
    }
    .nav{
      background-color: #ffcc00;
      border-radius: 0%;

    }
    .input-group{
      width: 250%;
      min-width: 100%;
      max-width: 250%;
    }

    /* Add a gray background color and some padding to the footer */
    footer {
      background-color: #f2f2f2;
      padding: 25px;
    }

  .carousel-inner img {
      width: 100%; /* Set width to 100% */
      margin: auto;
      min-height:20px;
  }

  /* Hide the carousel text when the screen is less than 600 pixels wide */
  @media (max-width: 600px) {
    .carousel-caption {
      display: none;
    }
  }
  .spc{
    opacity: 0%;
  }
  </style>
  

Sprint_3/educahelp/templates/parciais/_messages.html
{% if messages %}
    <br>
    {% for message in messages %}
        <div class="alert {{ message.tags }}" role="alert">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

Sprint_3/educahelp/templates/parciais/_nav.html
{% load omfilters %}

<style>
    .navbar{
        background-color: #ffcc00;
        border-radius: 0%;
        border-color: #ffcc00;
    }
    #logoimg{
      padding-top: 5px;
      margin-top: 0px;
    }

    #navbarDropdown{
      color: black;
      background-color: #ffcc00;
    }
    #entrar{
      color: black;
    }
    #criar-conta{
      color: black;
    }
    #nome{
      color: black;
    }
</style>



<nav class="navbar navbar-inverse navbar-expand-lg">
    <div class="container-fluid">
        <a class="navbar-left" href="{% url 'produto:lista' %}">
          <img src="https://raw.githubusercontent.com/RoyaltyDev/Projeto_integrador_2020-2/master/imagens/educahelp.png" width="80" height="40" class="d-inline-block align-top" alt="" loading="lazy" id="logoimg">
        </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <form class="form-inline" method="GET" action="{% url 'produto:busca' %}" style="margin-left: 30%;">
        <input name="termo" value="{{ request.GET.termo }}" class="form-control" type="search" style="min-width:300px;"

            placeholder="Busca" aria-label="Busca">
        <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
    </form>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="nav navbar-nav navbar-right">
            {% if request.user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'perfil:meus_pedidos' %}" id="nome"> <strong> Meus Conteúdos </strong> </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'produto:lista' %}" id="nome"> <strong> Olá! {{ request.user }} </strong> </a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
                    <strong>Conta</strong>
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item " href="{% url 'perfil:criar' %}">Perfil</a>
                    {% if perms.global_permissions.pode_adicionar_conteudo %}
                    <a class="dropdown-item " href="http://localhost:8000/admin/produto/produto/add/" target="__blank">Adicionar conteúdo</a>
                    <a class="dropdown-item" href="{% url 'pedido:export' %}">Baixar Relatório</a>
                    {% endif %}
                    <a class="dropdown-item " href="{% url 'pedido:lista' %}">Meus pedidos</a>
                    <a class="dropdown-item" href="{% url 'perfil:logout' %}">Sair</a>
                </div>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'perfil:criar' %}" id="entrar">Entrar</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'perfil:criar' %}" id="criar-conta">Criar conta</a>
            </li>
            {% endif %}

            {% if request.session.carrinho %}
            <li class="nav-item">
                <a class="nav-link nav-cart-link active" href="{% url 'produto:carrinho' %}">
                    <span class="nav-cart-text mr-1 text-dark">

                    </span>
                    <span class="nav-cart-count mr-1 text-dark">
                        <strong>{{ request.session.carrinho|cart_total_qtd }}x</strong>
                    </span>
                    <span class="nav-cart-icon mr-2 text-dark">
                        <i class="fas fa-shopping-cart text-dark"></i>
                    </span>
                </a>
            </li>
            {% endif %}


        </ul>
    </div>
    </div>
</nav>

Sprint_3/educahelp/templates/parciais/_pagination.html
{% if is_paginated %}

<div class="col mt-3 mb-3">
    <div class="row">
        <div class="pagination">
            <ul class="pagination">
                {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page=1">&laquo;</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&lsaquo;</a>
                </li>
                {% endif %}

                {% for num in page_obj.paginator.page_range %}

                {% if page_obj.number == num %}
                <li class="page-item active">
                    <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                </li>
                {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                </li>
                {% endif %}

                {% endfor %}

                {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">&rsaquo;</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">&raquo;</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>
{% endif %}

Sprint_3/educahelp/templates/parciais/_pedido.html
{% load static %}
{% load omfilters %}

<div class="row">
    <div class="col">
        <h3>{{ pedido }}</h3>

        <div class="row mt-4">
            <div class="col-lg-2 font-weight-bold">Número do pedido:</div>
            <div class="col-lg-4">{{ pedido.id }}</div>
            <div class="col-lg-2 font-weight-bold">Total a pagar:</div>
            <div class="col-lg-4">{{ pedido.total|formata_preco }}</div>

            <div class="col-lg-2 font-weight-bold">QTD. Itens:</div>
            <div class="col-lg-4">{{ pedido.qtd_total }}</div>
            <div class="col-lg-2 font-weight-bold">Status:</div>
            <div class="col-lg-4">{{ pedido.get_status_display }}</div>
        </div>

        <div class="row mt-4">
            <div class="col">
                <h3>Produtos</h3>
            </div>
        </div>

        <div class="table-responsive mt-3">
            <table class="table">
                <tr>
                    <th class="d-none d-lg-block">Imagem</th>
                    <th>Produto</th>
                    <th>V.</th>
                    <th>QTD.</th>
                    <th>Total</th>
                </tr>

                {% for linha in pedido.itempedido_set.all %}
                <tr>
                    <td class="d-none d-lg-block">
                        <img class="cart-img" src="{% get_media_prefix %}{{ linha.imagem }}">
                    </td>
                    <td>{{ linha.produto }}</td>
                    <td>{{ linha.variacao }}</td>
                    <td>{{ linha.quantidade }}</td>
                    <td>
                        {% if linha.preco_promocional %}
                        {{ linha.preco_promocional|formata_preco }}
                        {% else %}
                        {{ linha.preco|formata_preco }}
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}

            </table>
        </div>
    </div>
</div>

Sprint_3/educahelp/templates/parciais/contato.html
<!doctype html>
<html lang="pt-BR">

<head>
    {% include 'parciais/_head.html' %}
    <title>{% block titulo %}{% endblock %}</title>
    
</head>
<style>


.tx1{
    position: absolute;
    width: 185px;
    height: 60px;
    left: 70px;
    top: 100px;
    
    font-style: normal;
    font-weight: bolder;
    font-size: 20px;
    line-height: 12px;

}

.fc{
    position: absolute;
    left: -2px;
    top: 130px;

}






</style>

<body>
    {% include 'parciais/_nav.html' %}
    
        {% include 'parciais/_messages.html' %}
        {% block conteudo %}{% endblock %}
    </main>
    <img src="https://raw.githubusercontent.com/RoyaltyDev/Projeto_integrador_2020-2/master/imagens/faleconosco.PNG"  style="width: 180px;"  alt="Image" class= "fc1">
    <br>
    <div class="col-lg mt-3">
    <p style="font-weight: bolder;">Nome: Antonio Egydio São Thiago Graça</p>
    <p style="font-weight: bolder;">E-mail: antonio.graca@fatec.sp.gov.br</p>
    <p style="font-weight: bolder;">Telefone:</p>
    <p style="font-weight: bolder;">LinkedIn:</p>


    <p></p>   
    <br>
    <br>
   
    <div>
    <img src="https://raw.githubusercontent.com/RoyaltyDev/Projeto_integrador_2020-2/master/imagens/falecom osdesenvolvedores.PNG"  style="width: 180px;" style="left: 45px;" alt="Image" class= "fc">
    </div>
    <br>
    <p></p>   
    <p></p>   
    <p></p>   
    <p></p>  
    <p></p>
    <p></p>   
    <p></p>   
    <p></p>   
    <p></p>  
    <p></p>  
    <p></p>  
    <p style="font-weight: bolder;">
        Guilherme Cleyton Pereira (Scrum Master) – <a href = "https://github.com/gui863" >Git Hub</a>, <a href = "https://www.linkedin.com/in/guilherme-cleyton-7993aa7a/">LinkedIn;</a>
    </p>
    <p style="font-weight: bolder;">
        Danielle Brito Evangelista – <a href = "https://github.com/DanielleBritoEvangelista">Git Hub</a>, <a href = "https://www.linkedin.com/in/danielle-brito-81b4381b8?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3BV7w%2BnMliT5CnzhdsWhACew%3D%3D">LinkedIn;</a>
    </p>
    <p style="font-weight: bolder;">
        Elias Ferreira de Faria - <a href = "https://github.com/elias31072002">Git Hub</a>, <a href = "https://www.linkedin.com/in/elias-ferreira-525ba41b6/">LinkedIn;</a>
    </p>
    <p style="font-weight: bolder;">
        Lucas Cesar Andrade Prado – <a href = "https://github.com/LucasACES">Git Hub</a>, <a href = "https://www.linkedin.com/in/lucas-c%C3%A9sar-2020k/">LinkedIn;</a>
    </p>
    <p style="font-weight: bolder;">
        Marcus Vinicius Augusto Rocha – <a href = "https://github.com/mvarocha">Git Hub</a>, <a href = "https://www.linkedin.com/in/marcus-vin%C3%ADcius-augusto-rocha-568bb8192/">LinkedIn.</a>
    </p>   









   





    </div>
    {% include 'parciais/_footer.html' %}

    
</body>

</html>